# Generated by Django 5.1.3 on 2024-11-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='product_id',
            new_name='listing_id',
        ),
    ]
