# Generated by Django 5.1.3 on 2024-11-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_product_id_bid_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='product_id',
        ),
    ]
