# Generated by Django 5.1.3 on 2024-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active_status',
            field=models.CharField(max_length=64),
        ),
    ]
